sudo: required
dist: trusty
language: scala
scala:
- 2.11.7
jdk:
- oraclejdk8
script:
- sbt +clean coverage +test && sbt coverageReport coverageAggregate
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
before_install:
- pip install --user codecov
- sudo chmod +x /usr/local/bin/sbt
after_success:
- codecov
- test "$TRAVIS_REPO_SLUG" == 'fulcrumgenomics/sopt' && test "$TRAVIS_PULL_REQUEST"
  == 'false' && test "$TRAVIS_BRANCH" == 'master' && sbt +publish
env:
  global:
  - secure: UMOsCpZywad7O1Oj03l+hDnaNsQt/vTJKF1K83nCgozMR6LTr9XltjL2YnfHs1t37q1ClFNXC2KDGf4IEVeOISl1W/i+gK9rSFP54V2h1vLn3LD7pvI3i4rMU0MOaIPxP7HgTUb9SulmfcQmDP4wAoo4WQXO4tal2ETn+7JPngLIAw/cZebMEroh0ro3Di3UEr/k+BFUzQlhsKyl3BGWZLCssiHRdEuHal+yb80czBgFX5aFHRwlbwTGHmdQ0QPhicj4YQly/DHO53J8YrRLNxmYy1LQUxPujWMY/opAvJQfZrwuGATnmqUPJc5pd0HMqPV1UfRaA+bFmMnkpTy2YobxHzxxFwGLgQ6b8wE1U6yEM34OniltJoPk0rMJdaKiYazcKd3GIlo0rcVMb4Ul81SfgyCi7JNe2chQVEF9eoYo4C18muS9yvs0AltCNimqj8Zd5VL0q6ynsK7oMoY0ot5ZeP+35OgxLsCipCnG3ysJ/JKhFuce4N5m8HiFY4QRumATcquk5fGHE4waVdq+llXivHFu3mqPAYrNJ8B74CEJIkzN+kUl4AOzJJKzmvFluxf096HDn7sjOPFBv8//tx2tQPI9RInp1DbAcO64UDKDHKBfo0EV41ruik8VibpZE8N1DcXpWX6PSZXIQ7wvKgVtAS7nreREOyQvMVBF03Y=
  - secure: eRvt4aBa+PNZChKCCKWJZXcOYot0MEAITej9gqEuSUvsLwx3IV3zC4NrRhiNFteaU1pbO+GYPHUwjDDtilIjystpaTjAqC7ub53QCEEKsUp5inNAkWItdjcfz0yW2ep3sYWnkyc8kfBZB8sLOFcuxtHuXXV97iLuVaOBsmYdbUJE7ZXf+qzPfeLjlhXUf2EQmjbe/9eXF2kK/6McLaECNSm1tX1KfknmxEb2EkprNCtnioQrBwEKkyt5k+0XvW5/pf9u/sK63ZrHwYlpMz/IJ9jvJcjSSIVT/KRD4Q1rE5+PCKMwc7X+beHw3Vepp7+12NfsOLi9mrtyrk/BUjinCZs7U89dJuNbB+zNBfQY1+waXFb6rHoNBHHehcscmmZHMTdFSK7PBkBhpZtyeIBakVXiE+apnKtivXapbfC+XA/8sngKhcLeHhNQOUd9I2rdTJ9b1OGVmPZX8YbPXZzC5RTnJ4I2ffBIrWRvq5jqOjWXm576RqihHdlkIFir9szS9VlWT6dsTnwojSk0D9oL1c80Svenbn8gOzkiDg/MqgJAE/uxvh9tV5kblXSVghmUuK9Hkigr7oBlmdMd3mNF1FIY5kMnxQ/in37P9dt1krXcL+FHuOJOnTsvSq3ywimRuCl+zz4z0y6PoraInHEKxrYXpYDNnb4Kk1tuZMKdzD4=
