name: unit tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-24.04
    environment: github-actions
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Scala
        uses: olafurpg/setup-scala@v12
        with:
          java-version: adopt-openj9@1.8.0-292
      - name: Unit Tests
        run: |
          set -e
          sbt +clean coverage +test && sbt coverageReport coverageAggregate && (find $HOME/.sbt -name "*.lock" | xargs rm) && (find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm)
      - name: Code Coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
      - name: Cache .ivy2
        uses: actions/cache@v4
        with:
          path: ~/.ivy2
          key: ${{ runner.os }}-ivy2-${{ hashFiles('**/build.sbt') }}
      - name: Cache .sbt
        uses: actions/cache@v4
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.properties') }}
  release:
    if: github.repository == 'fulcrumgenomics/sopt' && github.ref == 'refs/heads/main'
    
    needs: test
    runs-on: ubuntu-24.04
    environment: github-actions
    env:
      SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
      SONATYPE_PASS: ${{ secrets.SONATYPE_PASS }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Scala
        uses: olafurpg/setup-scala@v12
        with:
          java-version: adopt-openj9@1.8.0-292
      - name: Upload to Sonatype
        run: |
          sbt +publish
